URLs:
    SOLR: "http://quest.ms.mff.cuni.cz/namuddis/qasolr/wiki_test/query?q={query}&wt=json&fl=title,first_paragraph,url,score"
    UDPIPE: "http://lindat.mff.cuni.cz/services/udpipe/api/process?tokenizer&tagger&data={query}"
    KOREKTOR: "http://lindat.mff.cuni.cz/services/korektor/api/correct"
    WIKI: "https?//cs.wikipedia.org*"
    LOGIC: "https?//www.logickaolympiada.cz*"
    LINDAT_EN2CS: "https://lindat.mff.cuni.cz/services/translation/api/v2/models/en-cs?src=en&tgt=cs"
    LINDAT_CS2EN: "https://lindat.mff.cuni.cz/services/translation/api/v2/models/cs-en?src=cs&tgt=en"
QA_MODEL_PATH: "multilingual_qaqg"
HC_RESPONSES_PATH: "data/handcrafted_responses.yml"
INTENT_MODEL_PATH: "edubot/educlf/trained_model"
SENTENCE_REPR_MODEL: "paraphrase-multilingual-mpnet-base-v2"
CHITCHAT: 
    MODEL: "facebook/blenderbot-400M-distill"
    DECODE_PARAMS: {max_length: 100, temperature: 1.5,top_p: 0.9, repetition_penalty: 1.1, top_k: 50, do_sample: True}
LOGFILE_PATH: None
STOPWORDS_PATH: "data/stopwords.txt"
CHITCHAT_INTENTS:
    - "chch"
