URLs:
    SOLR: "http://quest.ms.mff.cuni.cz/namuddis/qasolr/wiki_test/query?q={query}&wt=json&fl=title,first_paragraph,url,score"
    UDPIPE: "http://lindat.mff.cuni.cz/services/udpipe/api/process?tokenizer&tagger&data={query}"
    CHITCHAT: "http://localhost:8200"
    KOREKTOR: "http://lindat.mff.cuni.cz/services/korektor/api/correct"
    WIKI: "https?//cs.wikipedia.org*"
    LOGIC: "https?//www.logickaolympiada.cz*"
QA_MODEL_PATH: "multilingual_qaqg"
HC_RESPONSES_PATH: "data/handcrafted_responses.yml"
INTENT_MODEL_PATH: "edubot/educlf/trained_model"
SENTENCE_REPR_MODEL: "paraphrase-multilingual-mpnet-base-v2"
LOGFILE_PATH: None
STOPWORDS_PATH: "data/stopwords.txt"
CHITCHAT_INTENTS:
    - "chch"
