import edubot.remote_services
import yaml
config = yaml.load(open('configs/default_config.yaml', 'r'), Loader=yaml.loader.SafeLoader)
RSH = edubot.remote_services.RemoteServiceHandler(config, set())
print(RSH.postprocess_gender('Jsem šťastná, že jsem tu mohla být.'))
print(RSH.postprocess_gender('Jsi šťastná?'))
print(RSH.postprocess_gender('Olga je šťastná.'))
print(RSH.postprocess_gender('Šla jsem a koupila pět rohlíků.'))
print(RSH.postprocess_gender('Jsem spisovatelka na volné noze.'))
print(RSH.postprocess_gender('Vyučila jsem se prodavačkou.'))
print(RSH.postprocess_gender('Vyučila jsem se na prodavačku.'))
print(RSH.postprocess_gender('Jsem zaměstnaná jako uklízečka'))
print(RSH.postprocess_gender('Byla jsem zaměstnaná jako uklízečka'))
print(RSH.postprocess_gender('Jsem ráda, že jsem tady'))
print(RSH.postprocess_gender('Byla jsem zaměstnaná jako vědecká a akademická pracovnice'))
print(RSH.postprocess_gender('Já jsem byla zaměstnaná jako vědecká a akademická pracovnice univerzity.'))
print(RSH.postprocess_gender('Mám ho ráda'))
print(RSH.postprocess_gender('Cítila jsem se měšťankou.'))
print(RSH.postprocess_gender('Byla jsem studentkou.'))
print(RSH.postprocess_gender('Byla jsem zvolena poslankyní.'))
print(RSH.postprocess_gender('Zvolili mě poslankyní.'))
print(RSH.postprocess_gender('Mám propadlou občanku.'))
